### ISSUE TITLE
Keeps showing "Roles are being retrieved from Kubernetes"

### ISSUE THREAD

**Issue by ahmetb** [jasonrichardsmith/rbac-view#16]
I get this on my GKE cluster:

![image](https://user-images.githubusercontent.com/159209/47270600-d8efd200-d522-11e8-8354-82eb6b31cdde.png)

- Refreshing doesn't make it go away. 
- My kubectl works fine against the cluster at the moment.
- I tried adding "-v 10" flag to get some logs, but didn't get anything.

Looks like a very cool plugin, waiting to try this out! 🙌

**Comment by jasonrichardsmith** [comment]
The loading can take several minutes, but there is also a bug where it does not check the KUBECONFIG env variable.

Can you give me details on your OS and where the kubeconfig is located?  Is there any output on the cli when you run the command, after waiting a few minutes?

**Comment by jasonrichardsmith** [comment]
This should be resolved for KUBECONFIG in #17
